from django.urls import path
from . import views

urlpatterns = [
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.employee_create, name='employee_create'),
    path('employees/<int:pk>/', views.employee_detail, name='employee_detail'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee_edit'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee_delete'),
    path('employees/export/', views.export_employees_excel, name='export_employees_excel'),
    path('positions/', views.position_list, name='position_list'),
    path('positions/add/', views.position_create, name='position_create'),
    path('positions/<int:pk>/edit/', views.position_edit, name='position_edit'),
    path('positions/<int:pk>/delete/', views.position_delete, name='position_delete'),
    path('subscription-plans/', views.subscription_plan_list, name='subscription_plan_list'),
    path('subscription-plans/add/', views.subscription_plan_create, name='subscription_plan_create'),
    path('subscription-plans/<int:pk>/edit/', views.subscription_plan_edit, name='subscription_plan_edit'),
    path('subscription-plans/<int:pk>/delete/', views.subscription_plan_delete, name='subscription_plan_delete'),
    path('subscriptions/', views.subscription_list, name='subscription_list'),
    path('subscriptions/export/', views.export_subscriptions_excel, name='export_subscriptions_excel'),
    path('clients/without-zone/', views.clients_without_zone, name='clients_without_zone'),
    path('zones/', views.zone_list, name='zone_list'),
    path('zones/add/', views.zone_create, name='zone_create'),
    path('zones/<int:pk>/', views.zone_detail, name='zone_detail'),
    path('zones/<int:pk>/edit/', views.zone_edit, name='zone_edit'),
    path('zones/<int:pk>/delete/', views.zone_delete, name='zone_delete'),
    path('zones/<int:pk>/clients/', views.zone_clients_manage, name='zone_clients_manage'),
    path('zones/<int:pk>/subscriptions/', views.zone_subscriptions_manage, name='zone_subscriptions_manage'),
    path('zones/<int:pk>/subscriptions/export/', views.export_zone_subscriptions_excel, name='export_zone_subscriptions_excel'),
    path('zones/<int:pk>/employees/', views.zone_employees_manage, name='zone_employees_manage'),
    path('zones/<int:pk>/finance/', views.zone_finance_manage, name='zone_finance_manage'),
    path('zones/<int:pk>/finance/export/', views.export_zone_finance_excel, name='export_zone_finance_excel'),
    path('zones/<int:pk>/clients/export/', views.export_zone_clients_excel, name='export_zone_clients_excel'),
    path('zones/<int:pk>/quartiers/add/', views.quartier_create, name='quartier_create'),
    path('zones/<int:pk>/employees/export/', views.export_zone_employees_excel, name='export_zone_employees_excel'),
    path('zones/<int:pk>/clients/add/', views.zone_client_create, name='zone_client_create'),
    path('zones/<int:zone_pk>/clients/<int:client_pk>/edit/', views.zone_client_edit, name='zone_client_edit'),
    path('zones/<int:zone_pk>/clients/<int:client_pk>/delete/', views.zone_client_delete, name='zone_client_delete'),
    path('clients/<int:pk>/card/', views.client_card, name='client_card'),
    path('clients/<int:pk>/payments/', views.client_payment_history, name='client_payment_history'),
    path('subscriptions/<int:pk>/toggle-status/', views.subscription_toggle_status, name='subscription_toggle_status'),

    path('zones/<int:pk>/employees/add/', views.zone_employee_create, name='zone_employee_create'),
    path('zones/<int:pk>/subscriptions/add/', views.zone_subscription_create, name='zone_subscription_create'),
    path('subscriptions/<int:pk>/edit/', views.subscription_edit, name='subscription_edit'),
    path('subscriptions/<int:pk>/delete/', views.subscription_delete, name='subscription_delete'),
    path('zones/<int:pk>/invoices/add/', views.zone_invoice_create, name='zone_invoice_create'),
    path('invoices/<int:pk>/pay/', views.zone_invoice_pay, name='zone_invoice_pay'),
    path('zones/<int:pk>/clients/pay-all/', views.zone_invoice_pay_all, name='zone_invoice_pay_all'),
    path('invoices/<int:pk>/print/', views.invoice_print, name='invoice_print'),
    path('employees/<int:pk>/print/', views.employee_print, name='employee_print'),
]
