# Generated by Django 5.1.15 on 2026-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_invoice_id_alter_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('ACOMPTE', 'Acompte'), ('PAIEMENT', 'Paiement'), ('COMPTE', 'Solde')], default='PAIEMENT', max_length=20),
        ),
    ]
