# Generated by Django 5.1.15 on 2026-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_is_validated_payment_validated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('PAIEMENT', 'Paiement')], default='PAIEMENT', max_length=20),
        ),
    ]
