# Generated by Django 5.1.15 on 2026-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_alert_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
