# Generated by Django 5.1.15 on 2026-06-13 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice_last_alert_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('synced', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.CharField(default='LOCAL_SITE', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SALARY', 'Salaires'), ('RENT', 'Loyer'), ('EQUIPMENT', 'Matériel'), ('FUEL', 'Carburant'), ('MAINTENANCE', 'Entretien'), ('TAXES', 'Impôts & Taxes'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
