# Generated by Django 5.1.15 on 2026-06-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Physique', 'Physique'), ('Autre', 'Autre')], default='Mobile Money', max_length=50),
        ),
    ]
