# Generated by Django 5.0.14 on 2026-05-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.zone'),
        ),
    ]
