# Generated by Django 5.1.15 on 2026-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_phone_number_2_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
