# Generated by Django 5.1.15 on 2026-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='INFINITY', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('primary_color', models.CharField(default='#010694', help_text='Hex code for primary color (e.g. #010694)', max_length=7)),
                ('secondary_color', models.CharField(default='#2435c9', max_length=7)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la société',
                'verbose_name_plural': 'Paramètres de la société',
            },
        ),
    ]
