# Generated by Django 5.1.15 on 2026-05-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_companysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zone',
        ),
    ]
