# Generated by Django 5.1.15 on 2026-05-15 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_address_remove_user_phone_number_and_more'),
        ('business', '0003_employee_address_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='site_id',
            field=models.CharField(default='LOCAL_SITE', max_length=50),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.zone'),
        ),
    ]
