# Generated by Django 5.1.15 on 2026-05-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companysettings_site_id_companysettings_synced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ZONE_MANAGER', 'Chef de Zone'), ('ACCOUNTANT', 'Comptable'), ('CLIENT', 'Client'), ('SHAREHOLDER', 'Actionnaire')], default='CLIENT', max_length=20),
        ),
    ]
