# Generated by Django 5.1.15 on 2026-06-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quartier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
