# Generated by Django 5.1.15 on 2026-06-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_quartier'),
        ('business', '0006_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.quartier'),
        ),
    ]
