# Generated by Django 5.1.15 on 2026-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_quartier'),
        ('business', '0007_alter_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zones',
            field=models.ManyToManyField(blank=True, related_name='managers', to='business.zone'),
        ),
    ]
