# Generated by Django 5.1.15 on 2026-06-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fixed_due_date',
            field=models.DateField(blank=True, help_text="Date d'échéance fixe pour les paiements MoMo", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uses_momo_payment',
            field=models.BooleanField(default=False, help_text='Si le client paie via Mobile Money'),
        ),
    ]
