# Generated by Django 5.1.15 on 2026-06-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_fixed_due_date_user_uses_momo_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ZONE_MANAGER', 'Chef de Zone'), ('ACCOUNTANT', 'Comptable'), ('AGENT', 'Agent'), ('CLIENT', 'Client'), ('SHAREHOLDER', 'Actionnaire')], default='CLIENT', max_length=20),
        ),
    ]
