"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys

import pymysql

pymysql.install_as_MySQLdb()

from pathlib import Path

# ── Chargement du fichier .env (sans dépendance externe) ───────────────────
# Lit CLEAN/.env et expose les variables dans os.environ. Si python-dotenv est
# installé, on l'utilise ; sinon on parse manuellement.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    try:
        from dotenv import load_dotenv

        load_dotenv(env_path)
        return
    except ImportError:
        pass
    with env_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            key, value = key.strip(), value.strip()
            # Ne pas écraser une variable déjà présente dans l'environnement
            os.environ.setdefault(key, value)


_load_env()


def _env(key, default=None):
    """Retourne la valeur d'environnement, en gérant les booléens/listed."""
    return os.environ.get(key, default)


def _env_bool(key, default=False):
    val = os.environ.get(key)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


def _env_list(key, default=None):
    val = os.environ.get(key)
    if not val:
        return default or []
    return [item.strip() for item in val.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# (BASE_DIR already defined above for .env loading)

# Quand l'app tourne depuis un bundle PyInstaller, les fichiers
# modifiables (db, media, static collecté) sont à côté de l'exécutable.
if getattr(sys, "frozen", False):
    RUNTIME_DIR = Path(sys.executable).parent
else:
    RUNTIME_DIR = BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env(
    "SECRET_KEY", "django-insecure-25x*z(@tj17&a)3j31so^7tmtfti1(ddif#@cua9yt0@s$db&x"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", ["*"])


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if you want to use unfold filters
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "django_cron",
    "rest_framework",
    "django_extensions",
    # Local apps
    "accounts",
    "business",
    "finance",
    "notifications",
    "sync_engine",
]

AUTH_USER_MODEL = "accounts.User"

CRON_CLASSES = [
    "sync_engine.cron.SyncDataCronJob",
    "sync_engine.cron.DeactivateDelinquentClientsCronJob",
    "sync_engine.cron.LatePaymentNotificationCronJob",
    "sync_engine.cron.SubscriptionExpiryNotificationCronJob",
]

CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS", ["https://omerpay.share.zrok.io"]
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "accounts.middleware.ReadOnlyMiddleware",
    "sync_engine.middleware.AutoSyncMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.company_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database Routers
DATABASE_ROUTERS = ["sync_engine.router.SyncRouter"]

# Live Mode: 'LOCAL', 'CLOUD', or 'AUTO'
# 'AUTO' will try to connect to cloud, fallback to local if unreachable
LIVE_MODE = _env("LIVE_MODE", "AUTO")

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": RUNTIME_DIR / "db.sqlite3",
    },
    "cloud": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": _env("CLOUD_DB_NAME", "dhavant_db"),
        "USER": _env("CLOUD_DB_USER", "dhavant"),
        "PASSWORD": _env("CLOUD_DB_PASSWORD", "Brazzaville0!"),
        "HOST": _env("CLOUD_DB_HOST", "mysql-dhavant.alwaysdata.net"),
        "PORT": _env("CLOUD_DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

LOGIN_REDIRECT_URL = "accounts:login_redirect"
LOGOUT_REDIRECT_URL = "accounts:login"

# Sync settings
SITE_ID = _env("SITE_ID", "SITE_PARIS_01")
CLOUD_SYNC_URL = _env(
    "CLOUD_SYNC_URL", "https://clean-cloud-api.herokuapp.com/api/sync/"
)
CLOUD_API_KEY = _env("CLOUD_API_KEY", "your-secret-key-here")

# OpenPay settings
OPENPAY_API_KEY = _env(
    "OPENPAY_API_KEY",
    "s8bcb05294537e02f5d6f66a",
)
OPENPAY_URL = _env("OPENPAY_URL", "https://api.openpay-cg.com/v1/payment-link")

STATIC_URL = "/static/"
STATIC_ROOT = RUNTIME_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = RUNTIME_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "INFINITY Admin",
    "SITE_HEADER": "INFINITY Management",
    "SITE_SYMBOL": "infinity",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "239 240 255",
            "100": "224 226 255",
            "200": "195 199 255",
            "300": "154 160 255",
            "400": "109 112 252",
            "500": "67 70 239",
            "600": "43 43 209",
            "700": "34 32 170",
            "800": "30 28 137",
            "900": "1 6 148",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}
