# Generated by Django 5.1.15 on 2026-05-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_position_alter_employee_id_alter_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
