# Generated by Django 5.1.15 on 2026-05-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_employee_address_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
