# Generated by Django 5.1.15 on 2026-05-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='characteristics',
            field=models.TextField(blank=True, help_text='Liste des caractéristiques, une par ligne.'),
        ),
    ]
